cloud-gov/federalist.18f.gov

- pages/index.md
Copyedit and replacing some outdated info (more edits to come!). cc @jeremiak
> Updating the main page

- pages/index.md
I think this fixes https://github.com/18F/federalist/issues/355.
> typo fix, "git" -> "fit"

- pages/index.md
> Refine content on help docs landing page

- pages/using-federalist.md
> Refine content on Federalist tutorial page

- pages/using-federalist/launch-checklist.md
> Refine content on the Federalist launch checklist

- pages/custom-templates.md
> Refine content on custom templates page

- pages/how-federalist-works.md
This commit adds and describes all Federalist repos
> add the other Federalist repos to documentation

- pages/using-federalist/customer-responsibilities.md
Added a note to fix the issue that came up here: https://gsa-tts.slack.com/archives/federalist-support/p1483736457000050
> add note on GitHub required permissions

- pages/using-federalist.md
Fixes a typo, formats a couple things with backticks.
> Fix a typo and format some slugs

- pages/how-federalist-works/custom-urls.md
- pages/using-federalist/launch-checklist.md
> overhauled the custom URL page

- pages/how-federalist-works/included-with-federalist.md
> add CMS list link

- pages/how-federalist-works/custom-urls.md
> add info about the first scan in the go-live process

- _config.yml
- pages/using-federalist/instructional-demos.md
> add instructional videos

- pages/how-federalist-works/custom-urls.md
Thanks @andrewmaier! Would welcome comments.
> better explain custom URLs

- _config.yml
- pages/how-federalist-works/site-wide-alert.md
This commit contains instructions for setting a site-wide error.
> Add instructions for setting a site wide error

- pages/custom-templates.md
- pages/how-federalist-works.md
- pages/how-federalist-works/cloud-gov-setup.md
- pages/how-federalist-works/running-federalist-locally.md
ref: https://github.com/18F/federalist/issues/902
> Change "federalist-docker-build" -> "federalist-garden-build"

- pages/custom-templates.md
- pages/how-federalist-works/included-with-federalist.md
- pages/using-federalist.md
Also fixed some minor spelling and markdown-linting-related stuff.
Related: https://github.com/18F/federalist-garden-build/pull/64
> Add language about experimental hugo support

- pages/how-federalist-works.md
... in section explaining federalist-garden-build
> Remove outdated note about "docker"

- pages/how-federalist-works/cloud-gov-setup.md
Just turning some un-linked URLs into links.
> Turn urls into links

- pages/index.md
> Update with a period

- pages/index.md
So much spam of people trying to do SQL injection via the form. :/
> Add clarification for bug bounty folks

- pages/how-federalist-works/cloud-gov-setup.md
- pages/how-federalist-works/deploying-federalist.md
This PR is an update to our docs to reference CircleCI in place of Travis(CI). Ref https://github.com/18f/federalist/issues/922.
> Update Travis references to CircleCI

- _config.yml
- pages/content-guide/adding-search.md
Add recommendation to use DigitalGov search and links to their documentation/registration page.
ref #85 and https://github.com/18F/federalist/issues/392
> add digitalgov search recommendation

- pages/how-federalist-works/cloud-gov-setup.md
ref https://github.com/18f/federalist/issues/1139
> adjust docs to mention separate deployer services

- pages/index.md
In response to https://github.com/18F/writing-lab/issues/276#issuecomment-327631338
> Copy editing + tone edits

- assets/css/uswds-overrides.css
- pages/about-federalist/example-sites.md
https://federalist-proxy.app.cloud.gov/preview/18f/federalist-docs/wslack-screenshot-style/pages/about-federalist/example-sites/
> create screenshot style name and edit screenshot page

- pages/using-federalist/templates.md
Inspiration: https://github.com/18f/federalist-docs/edit/master/pages/about-federalist/example-sites.md
> edit templates page to use collections and better screenshot formats

- _includes/head.html
- pages/using-federalist/templates.md
also fix a typo
(just something I noticed while looking into the search integration)
> add favicon link to head.html

- _config.yml
- _data/navigation.yml
- _includes/navigation.html
- _includes/scripts.html
- pages/content-guide/adding-search.md
Check it out on the branch preview build: https://federalist-proxy.app.cloud.gov/preview/18f/federalist-docs/123-digitalgov-search/
> Integrate search.gov

- pages/using-federalist/templates.md
Not to be merged until after the main app is updated with the template
> Add report template to list

- pages/using-federalist/included-with-federalist.md
When correcting another copy of this in https://github.com/18F/federalist-docs/pull/166 I didn't notice this one
> WordPress is stylized in CamelCase

- pages/how-federalist-works/for-federalist-developers.md
This wasn't rendering correctly.
> fix spacing issue for the local branching

- pages/how-federalist-works/cloud-gov-setup.md
> Add memory and disk args to federalist-build-container cf push command

- pages/how-federalist-works/how-builds-work.md
> add info about build environment variables

- _data/navigation.yml
- pages/using-federalist/support.md
Created for https://github.com/18F/federalist-docs/issues/195
> create support page

- _config.yml
- _includes/scripts.html
Adding DAP via config as well as updating the GA code.
There were previously 2 versions of the GA code installed and it was causing conflicts. 
CC @wslack
> Adding DAP and updating GA code

- pages/for-federalist-developers/cloud-gov-setup.md
And add a sentence about memory and disk space for the build containers. Ref https://github.com/18F/federalist/issues/1438
> Update container memory argument

- pages/for-federalist-developers/cloud-gov-setup.md
- pages/how-federalist-works/index.md
redis has not been used for a while, these were just old references
ref #206
> remove references to redis

- pages/for-federalist-developers/cloud-gov-setup.md
without the comma I missed this sentence first pass.
> missing comma

- pages/404.md
Reverts 18F/federalist-docs#247
> Revert "test removing the slash"

- pages/how-federalist-works/how-builds-work.md
Adds both a note about how to use the option and what it is for.
> Add information about the script only build option

- _data/navigation.yml
- pages/using-federalist/permissions.md
Preview: 
https://federalist-proxy.app.cloud.gov/preview/18f/federalist-docs/permissions/pages/using-federalist/access-permissions/
> Permissions

- pages/index.md
> edit features link

- pages/using-federalist/permissions.md
Improving docs around access permissions to align with the welcome e-mail
> add note re access permissions

- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
[![CircleCI](https://circleci.com/gh/18F/federalist.18f.gov/tree/remove_unused_deps.svg?style=svg)](https://circleci.com/gh/18F/federalist.18f.gov/tree/remove_unused_deps)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/federalist.18f.gov/remove_unused_deps/)
> remove unused dependencies

- _data/navigation.yml
- pages/how-federalist-works/bundler-on-federalist.md
> add bundler version instructions

- _data/screenshots.yml
- Fix link
[![CircleCI](https://circleci.com/gh/18F/federalist.18f.gov/tree/fix_afwerx_link.svg?style=svg)](https://circleci.com/gh/18F/federalist.18f.gov/tree/fix_afwerx_link)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/federalist.18f.gov/fix_afwerx_link/)
> fix afwerx link

- pages/using-federalist/permissions.md
> organizational github oauth

- _data/navigation.yml
- pages/how-federalist-works/renaming-site-repository.md
> Repo rename

- _config.yml
- Exclude development files from published site directory
> do not publish developer text in live site

- _data/case_studies.yml
- Phrasing on Login.gov case study
> Phrasing fixes

- pages/index.md
> Typo of GSA

- pages/index.md
> Fix typo in usability text

- pages/index.md
> A two-page overview

- pages/documentation/node-on-federalist.md
- pages/documentation/supported-site-engines.md
> change script only to node.js

- pages/documentation/index.md
Re: issue closes #410, this is to update documentation to include our support of private repos
> Updated documentation

- _data/navigation.yml
- pages/documentation/env-vars-federalist.md
- pages/documentation/node-on-federalist.md
> move build env vars to separate page

- pages/documentation/customization.md
> add security.txt info

- pages/documentation/env-vars-federalist.md
- pages/documentation/how-builds-work.md
- pages/documentation/supported-site-engines.md
> add instructions for custom env vars

- _data/case_studies.yml
**I think that I am doing this right.**
-Added additional success stories to the ab-homepage-redo-success branch
/cc @amirbey 
[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/ab-homepage-redo-success-BHadd/)
> Add CoE and Afwerx to the case studies data

- pages/index.md
> Bryanthales testingv2

- _sass/federalist.scss
> init add logo

- pages/documentation/permissions.md
sign in to federalist before organizational access request
-
-
-
> org access update

- pages/documentation/supported-site-engines.md
> add hugo extended

- _data/navigation.yml
- pages/documentation/customization.md
- pages/documentation/federalist-sandbox.md
- pages/documentation/getting-started-with-jekyll.md
- pages/documentation/how-builds-work.md
- pages/documentation/included-with-federalist.md
- pages/documentation/index.md
- pages/documentation/instructional-demos.md
- pages/documentation/launch-checklist.md
- pages/documentation/migration-guide.md
- pages/documentation/permissions.md
- pages/documentation/previews.md
- pages/documentation/templates.md
- pages/documentation/why-use-federalist.md
> Bryant formatting

- _data/navigation.yml
- pages/documentation/custom-headers.md
- pages/documentation/federalist-json.md
Fixes issue(s) #365 .
- Add documentation for new custom cache-control headers feature
- Add documentation for new federalist.json file
[![CircleCI](https://circleci.com/gh/18F/federalist.18f.gov/tree/365-federalist-json-and-header-docs.svg?style=svg)](https://circleci.com/gh/18F/federalist.18f.gov/tree/365-federalist-json-and-header-docs)
[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/365-federalist-json-and-header-docs/)
> Added documentation for federalist.json file and custom headers.

- _data/navigation.yml
- _data/templates.yml
- pages/documentation/21st-century-idea.md
- pages/documentation/cloud-gov-setup.md
- pages/documentation/env-vars-federalist.md
- pages/index.md
- Fixed duplicated heading
- Update estimated visitors. 
- Remove old USWDS theme
- Add tagline that mentions 21st Century IDEA 
- Add 21st Century IDEA page
[![CircleCI](https://circleci.com/gh/18F/federalist.18f.gov/tree/clean_up_content.svg?style=svg)](https://circleci.com/gh/18F/federalist.18f.gov/tree/clean_up_content)
[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/clean_up_content/)
> Clean up and update content

- admin/config.yml
Otherwise they get removed when edits are made.
> Add widget for redirects

- _data/templates.yml
Fixes issue(s) #2485.
[![CircleCI](https://circleci.com/gh/18F/federalist.18f.gov/tree/2485-view-sample-links.svg?style=svg)](https://circleci.com/gh/18F/federalist.18f.gov/tree/2485-view-sample-links)
[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/2485-view-sample-links/)
> Update template site links

- pages/documentation/getting-started-with-netlify-cms.md
Add more clarity around how to configure Netlify CMS for use with Federalist.
/cc @jeremyzilar 
[![CircleCI](https://circleci.com/gh/18F/federalist.18f.gov/tree/dc/update-netlify-cms-docs.svg?style=svg)](https://circleci.com/gh/18F/federalist.18f.gov/tree/dc/update-netlify-cms-docs)
[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/dc/update-netlify-cms-docs/)
> Update netlify cms docs

- pages/documentation/rvm-on-federalist.md
- Updates documentation to reflect current default Ruby version of 2.6.6
> update ruby version

- _data/navigation.yml
[![CircleCI](https://circleci.com/gh/18F/federalist.18f.gov/tree/how-federalist-works-link.svg?style=svg)](https://circleci.com/gh/18F/federalist.18f.gov/tree/how-federalist-works-link)
[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/how-federalist-works-link/)
> fix nav link to How Federalist Works page

- _data/footer.yml
- Remove 18f logo from footer
[![CircleCI](https://circleci.com/gh/18F/federalist.18f.gov/tree/dc/remove-18f-logo.svg?style=svg)](https://circleci.com/gh/18F/federalist.18f.gov/tree/remove-18f-logo)
[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/remove-18f-logo/)
> Remove 18f logo

- pages/documentation/21st-century-idea.md
I was reading [this page](https://federalist.18f.gov/documentation/21st-century-idea/) and noticed a truncated paragraph. The content appears to have been copied from https://digital.gov/resources/21st-century-integrated-digital-experience-act/ in #363, so I took some bullet points from there to make the explanation flow more clearly.
cc @eddietejeda as the author of #363 :)
> Copy editing on 21st Century IDEA page

- README.md
- _config.yml
- _layouts/base.html
- admin/config.yml
- pages/documentation/cloud-gov-setup.md
- pages/documentation/custom-headers.md
- pages/documentation/for-federalist-developers.md
- pages/documentation/getting-started-with-netlify-cms.md
- pages/documentation/how-federalist-works.md
- pages/documentation/migration-guide.md
- pages/documentation/resources.md
- pages/documentation/site-wide-alert.md
- pages/documentation/supported-site-engines.md
Fixes issue(s) #417 .
- Replaces references to `master` branch with `main`
- Replaces references to `whitelist` with `allowlist`
[![CircleCI](https://circleci.com/gh/18F/federalist.18f.gov/tree/BRANCH_NAME.svg?style=svg)](https://circleci.com/gh/18F/federalist.18f.gov/tree/417-language)
[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/417-language/)
> Refactor language

- pages/documentation/customer-responsibilities.md
> add spf and dmarc info for users

- pages/features.md
Fixes issue(s) #426 
[![CircleCI](https://circleci.com/gh/18F/federalist.18f.gov/tree/426-slack-link.svg?style=svg)](https://circleci.com/gh/18F/federalist.18f.gov/tree/426-slack-link)
> Add some help text for folks who cannot access Google services

- pages/documentation/customization.md
- pages/documentation/included-with-federalist.md
content from OG PR: https://github.com/18F/federalist.18f.gov/pull/462
> ONLY Update 404 guidance

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
Updates rack dependency to resolve security issue.
> ONLY update rack and jekyll-rack

- pages/documentation/cloud-gov-setup.md
> Cloud gov setup update

- pages/documentation/permissions.md
> 90 days inactivity

- _data/navigation.yml
Addresses 18F/federalist#2720
- adds a link to statuspage in the header
> Add link to status page

- pages/documentation/forms.md
> Update GSA PTA content

- pages/documentation/customer-responsibilities.md
- pages/documentation/included-with-federalist.md
Fixes issue(s) #494 
- Add info on MTA-STS records
- Add our default headers included
[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/apb/update-dns-docs)
> Add language to improve best practice for customer DNS

- pages/documentation/customization.md
- adds note about custom 404 issues when testing in development site vs custom domain
/cc @davemcorwin 
> adds note to customization.md

- pages/documentation/custom-headers.md
> Update custom header example

- pages/documentation/node-on-federalist.md
Updates docs to reflect no long only installing node production deps
> update docs for installing node dev deps

- pages/documentation/custom-domains.md
Fixes issue(s) #520 .
- Document AAAA support on Federalist
[![CircleCI](https://circleci.com/gh/18F/federalist.18f.gov/tree/BRANCH_NAME.svg?style=svg)](https://circleci.com/gh/18F/federalist.18f.gov/tree/520-AAAA-docs)
[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/520-AAAA-docs/)
> Add documentation for AAAA records

- pages/documentation/before-you-launch.md
- pages/documentation/custom-domains.md
- pages/documentation/getting-started-with-jekyll.md
> Update launch checklist, custom domains and jekyll guides

- _data/navigation.yml
- pages/documentation/custom-headers.md
- pages/documentation/excludepaths-and-includepaths.md
- pages/documentation/federalist-json.md
- Documentation for  18f/federalist-garden-build#343
None
> Documentation for exclude and include paths and some other minor fixes

- pages/cloud-gov-pages.md
- Add pages migration info
/cc @apburnes 
[![CircleCI](https://circleci.com/gh/18F/federalist.18f.gov/tree/pages-migration.svg?style=svg)](https://circleci.com/gh/18F/federalist.18f.gov/tree/pages-migration)
[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/pages-migration/)
> add pages migration info

- _data/navigation.yml
- pages/documentation/large-file-handling.md
- pages/documentation/migration-guide.md
- Add documentation regarding large file handling
/cc @apburnes @hursey013 @Ephraim-G 
[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/ddb-large-file-handling/)
> Add documentation regarding large file handling
