cloud-gov/federalist.18f.gov

_config.yml
pages/how-federalist-works/running-federalist-locally.md

This commit adds a guide which provides some notes about running the different parts of Federalist locally in a development context.

Add guide to running Federalist locally

---

_config.yml
pages/how-federalist-works/cloud-gov-setup.md
pages/how-federalist-works/deploying-federalist.md
pages/how-federalist-works/deploying-to-cloud-gov.md

This PR adds a guide that covers deploying to cloud.gov's GovCloud environment.
~~Right now it only has information about managing / scanning the images but more will come.~~

Add cloud.gov deploy guide

---

pages/how-federalist-works/custom-urls.md

One question: what does this change do? Do the assets go into a different S3 folder, or does Jekyll tell a component browser to look for them at a different URL?

Add note that Federalist custom URL setting must be changed

---

pages/how-federalist-works/cloud-gov-setup.md

This file updates the docker-compose.yml example in the "cloud.gov Setup" guide.
For background on this look at coreos/clair#284.

Update docker-compose.yml example

---

_config.yml
pages/how-federalist-works/node-on-federalist.md

This commit documents how site owners can use Node.js with Federalist.
Note that the features described in this commit will not take effect
until 18F/federalist-docker-build#13 and 18F/federalist#680 are merged.

Document how to use Node with Federalist

---

pages/using-federalist/customer-responsibilities.md

This fixes a few typos, links cloud.gov, and makes a couple of minor tweaks for clarity.

Fix typos, minor clarity changes

---

pages/how-federalist-works/cloud-gov-setup.md

This commit adds instructions for setting up a GitHub OAuth application
while deploying to GovCloud. The absence of these instructions was
recently noted while deploying Federalist.

Cover GitHub OAuth setup in cloud.gov setup guide

---

pages/how-federalist-works/custom-urls.md

This commit updates the example command for creating a CDN distribution to use federalist-proxy instead of proxying directly from the S3 bucket.

Update CDN creation command to use federalist proxy instead of S3

---

pages/how-federalist-works/custom-urls.md

This adds a note about trailing slashes to the instructions for setting custom URLs.

Add note about trailing slash

---

assets/css/uswds-overrides.css

This fixes the issue around inconsistent line widths on list items when using the Standards. [We currently have an issue opened](https://github.com/18F/web-design-standards/issues/1682) for making this fix on the main code base. Adding this in so that [this pull request](https://github.com/18F/federalist-docs/pull/31) is no longer blocked.
Also, fixed the layout front matter for the override stylesheet to `null` from `none` and made that error going away 🎉

Add max-width for list items in main content area

---

pages/custom-templates.md
pages/index.md
pages/using-federalist.md
pages/using-federalist/customer-responsibilities.md

This commit removes references to the Federalist editor since the editor has been removed.
Ref 18f/federalist#770

Remove references to the editor

---

pages/custom-templates.md

The commit data was removed from the site config in 18f/federalist-docker-build#36. This commit removes the references to that data from the documentation.

Remove paragraph about commit data in site config

---

pages/index.md

This commit replaces SBST.gov with 18f.gsa.gov as an example of something you can build with Federalist on the home page.

Replace SBST.gov with 18f.gsa.gov on the homepage

---

pages/how-federalist-works/cloud-gov-setup.md

Since we use the cloud.gov space-deployer service, the credentials can occasionally expire. This commit adds documentation describing the process for updating the credentials when that happens.
Ref 18F/federalist#849

Add docs describing the process for rotating deployer credentials

---

_config.yml
pages/how-federalist-works/rvm-on-federalist.md

This commit adds instructions on how to use RVM to specify a ruby
version for a Federalist site.

Add instructions on specifying ruby version with RVM

---

pages/how-federalist-works/running-federalist-locally.md

The instructions for setting up Federalist locally were missing 2 instructions:
1. Instructions on creating a database
2. Instructions to run `npm run build` before starting the app
These were noticed during @jseppi's onboarding.
Ref #72

Add some missing instructions for running Federalist locally

---

pages/how-federalist-works/cloud-gov-setup.md

This commit adds docs to describe the work we did to setups the CDN route that routes traffic from federalist.18f.gov and federalist-staging.18f.gov to the appropriate app.

Add docs on setting up CDN route

---

pages/how-federalist-works/running-federalist-locally.md

ref https://github.com/18F/federalist/pull/1019
Note: I did not update the section of instructions for `federalist-builder` since that project is not switched to `yarn` yet.

Add yarn dependency and switch npm commands to yarn

---

_includes/footer.html
pages/how-federalist-works.md

Also slight styling adjustment to the footer to differentiate it from main content. Looks like this now:

Use correct URL for federalist-builder

---

pages/how-federalist-works/cloud-gov-setup.md

Rather than have our own clair instructions instructions, which can get out of date and become incorrect, this PR replaces them with links to the official docs.

Delegate clair setup instructions to original docs

---

pages/how-federalist-works/custom-urls.md

Just me being nitpicky :-) Also made formatting more consistent, and added a link to the cloud.gov docs.

make the custom URL setup steps an ordered list

---

pages/how-federalist-works/node-on-federalist.md

This commit adds documentation describing how and why to exclude the node_modules directory in a Federalist site.
Ref: https://github.com/18F/federalist/issues/735

Add docs on ignoring node modules

---

pages/how-federalist-works/cloud-gov-setup.md

Per deprecation of clair's analyze-local-images and the rest of the
discussion in https://github.com/18F/federalist/issues/1035.

Remove clair scanning information

---

_config.yml
_includes/navigation.html

Fix the main header link to point to the site root.
Also add the `site.title` value so that the title attribute doesn't look weird any more:
`->`
ref #144

Add link to site header and add site.title value

---

pages/how-federalist-works/cloud-gov-setup.md

Noticed while creating a test bucket for the new python publisher.

Remove spurious trailing `/site` from s3 command

---

_includes/scripts.html

Adding Google analytics for the federalist docs site 
Addresses issue https://github.com/18F/federalist/issues/1287

Adding Google analytics

---

pages/how-federalist-works/how-builds-work.md
pages/how-federalist-works/index.md

That base container image is no longer used in our garden build container. Ref #187.
Also removed a bit about the `github-pages` gem being pre-installed. It's not as far as I can tell, and I'm not sure if it ever was :) @jmhooper?

remove docker-ruby-ubuntu mentions

---

pages/for-federalist-developers/cloud-gov-setup.md

Update build container deployment instructions to reflect new reality of 4GB disk space.

Increase container disk space to 4 GB

---

pages/using-federalist/templates.md

The templates page currently displays the templates offered. This PR adds detail specific to how partners should view templates — both what they are and what they are not.

Add detail re: templates

---

_config.yml
_layouts/template.html
_templates/basic-report.md
_templates/landing-page.md
_templates/modern-team.md
_templates/uswds-default.md
pages/using-federalist/templates.md

From https://github.com/18F/federalist-uswds-template/pull/19#issuecomment-380281122, we decided that if Federalist provides official support for the templates, then the documentation should live with the official Federalist documentation vs on a wiki or GitHub README.
This introduces a Jekyll collection for the template pages.
We now include a link to the documentation on the template index page.
Here's what the Basic Report doc page looks like.

Template docs

---

_data/case_studies.yml

- corrects DOI reference (Department of _the_ Interior)
- fixes typo ("general")
- other minor edits

Corrects official agency name, typo in case studies

---

pages/index.md

Fixed the link for cio.gov. It was linking to fedramp.gov.
-
-
-

Fixed link for cio.gov

---

_data/navigation.yml
pages/how-federalist-works/monorepos-on-federalist.md

Fixes issue(s) #2137 .
- Add documentation for using monorepos on Federalist
/cc @eddietejeda 
[![CircleCI](https://circleci.com/gh/18F/federalist.18f.gov/tree/BRANCH_NAME.svg?style=svg)](https://circleci.com/gh/18F/federalist.18f.gov/tree/2137_document-monorepo-approach)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/federalist.18f.gov/2137_document-monorepo-approach/)

Added documentation for using monorepos on federalist

---

pages/index.md
spec/basic_spec.rb

Changed the original heading on the landing page to: There’s no new easier way to launch, maintain, and manage government sites 
Changed the subheading on the landing page to: Federalist is a publishing platform for modern, compliant government websites
[![CircleCI](https://circleci.com/gh/18F/federalist.18f.gov/tree/BRANCH_NAME.svg?style=svg)](https://circleci.com/gh/18F/federalist.18f.gov/tree/amirahaziz-patch-1)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/federalist.18f.gov/amirahaziz-patch-1/)

Changed heading & subheading taglines

---

pages/success-stories.md

Removed Success Story box detailing new customer as of Feb 28 2018. As changed top text to be full width instead of two-thirds. Also, chose to do it off the master since it was a quick fix and didn't want to wait for the broader Success Stories dev work to finish.
-Removed blue box with new customer on success stories page
-Changed text settings to be full width instead of two-thirds width
/cc @amirbey 
[![CircleCI] bh-remove-2018-new-customer-ss 
[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/bh-remove-2018-new-customer-ss/success-stories/)

Bh remove 2018 new customer ss

---

_config.yml

Every page, e.g. [Customer Responsiblities](https://federalist.18f.gov/documentation/customer-responsibilities/) has the title "<title> | Federalist Homepage". This removes the "Homepage" part, since many of these are not the homepage.
[![CircleCI](https://circleci.com/gh/18F/federalist.18f.gov/tree/adborden-patch-1.svg?style=svg)](https://circleci.com/gh/18F/federalist.18f.gov/tree/adborden-patch-1)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/federalist.18f.gov/adborden-patch-1/)

Remove "Homepage" from every page title

---

PULL_REQUEST_TEMPLATE.md
assets/js/index.js

Fixes issue(s) #348 .
- Temporarily adds JS to remove the `usa-sr-only` class from the search form to it is visible. Can be removed once `uswds-jekyll` is updated
/cc @eddietejeda @amirbey 
[![CircleCI](https://circleci.com/gh/18F/federalist.18f.gov/tree/348-search-input.svg?style=svg)](https://circleci.com/gh/18F/federalist.18f.gov/tree/348-search-input)
[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/348-search-input/)

Restore visibility of search input

---

_data/case_studies.yml

Starting with a low number makes the reach of Federalist sound super small
> Nine agencies use Federalist to host over 100 sites...
I made some edits to better frame this.
/cc @eddietejeda

edits to case studies summary

---

pages/documentation/rvm-on-federalist.md

Adds the current default Ruby version to the documentation.
[![CircleCI](https://circleci.com/gh/18F/federalist.18f.gov/tree/dc/add-ruby-version.svg?style=svg)](https://circleci.com/gh/18F/federalist.18f.gov/tree/dc/add-ruby-version)
[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/dc/add-ruby-version/)
This came out of a conversation on Slack with @stvnrlly .

Add Current default Ruby Version

---

pages/documentation/custom-headers.md

There was an H1 at the top of the page that duplicated the title of the page (which is also a H1)

removing duplicate heading

---

pages/documentation/21st-century-idea.md

- Updates the link text "check out" on the ["21st Century IDEA" page](https://federalist.18f.gov/documentation/21st-century-idea/) to be a complete sentence, describing the link destination as "21st Century IDEA resource on Digital.gov".
Currently, the link is presented as an incomplete sentence, with no context on where the link will navigate:
>To learn more about this law, [check out](https://digital.gov/resources/21st-century-integrated-digital-experience-act/).
See live: https://federalist.18f.gov/documentation/21st-century-idea/
Relevant guidance: https://content-guide.18f.gov/urls-and-filenames/#link-text
>This ultimately means that link text should be understandable independent of the text surrounding it. Avoid ambiguous link text like click …

Update IDEA link "check out" to describe link destination

---

pages/documentation/getting-started-with-netlify-cms.md

Fixes issue(s) #447 .
- Add documentation for Netlify CMS authentication requirements
[![CircleCI](https://circleci.com/gh/18F/federalist.18f.gov/tree/BRANCH_NAME.svg?style=svg)](https://circleci.com/gh/18F/federalist.18f.gov/tree/447-netlify-cms-auth-docs)
[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/447-netlify-cms-auth-docs/)

Add authentication requirements for users of Netlify CMS

---

_config.yml
_includes/analytics.html

Fixes issue(s) #450 .
- Configures DAP subagency
- Adds custom analytics header until upgrade to uswds-jekyll v5
[![CircleCI](https://circleci.com/gh/18F/federalist.18f.gov/tree/450-update-dap-subagency .svg?style=svg)](https://circleci.com/gh/18F/federalist.18f.gov/tree/450-update-dap-subagency )
[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/450-update-dap-subagency /)

450 update dap subagency

---

pages/documentation/federalist-json.md

Fixes issue(s) https://github.com/18F/federalist-garden-build/issues/281.
- Add docs for `fullClone` federalist.json config option
[![CircleCI](https://circleci.com/gh/18F/federalist.18f.gov/tree/fgb281-fullclone-config-option.svg?style=svg)](https://circleci.com/gh/18F/federalist.18f.gov/tree/fgb281-fullclone-config-option)
[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/fgb281-fullclone-config-option/)

Add docs for `fullClone` federalist.json config option

---

pages/documentation/how-builds-work.md

Nothing says "I appreciate you" quite like sharing another's typo.
Replaces ~our~ with out.

Typo fix in build docs

---

_config.yml

Adds url to ensure sitemap contains full urls

Add url to Jekyll config to fix sitemaps

---

pages/cloud-gov-pages.md

- The Pages transition banner links to [a page](https://federalist.18f.gov/cloud-gov-pages/) that says we'll "start publishing updates at the end of June, 2021." This PR changes that to "start publishing updates soon".

Adjust promised Pages updates from June 2021 to "soon"

---

pages/documentation/env-vars-federalist.md

Re issue(s) https://github.com/18F/federalist.18f.gov/issues/546.
- Add examples to default env vars documentation
[![CircleCI](https://circleci.com/gh/18F/federalist.18f.gov/tree/bh-env-var-docs.svg?style=svg)](https://circleci.com/gh/18F/federalist.18f.gov/tree/bh-env-var-docs)
[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/bh-env-var-docs/)

Add examples to default env vars documentation

---

pages/documentation/rvm-on-federalist.md

- Add information about Ruby maintenance and EOL
[![CircleCI](https://circleci.com/gh/18F/federalist.18f.gov/tree/bh-ruby-eol.svg?style=svg)](https://circleci.com/gh/18F/federalist.18f.gov/tree/BRANCH_NAME)
[:sunglasses: PREVIEW](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/bh-ruby-eol/)

Add documentation about Ruby EOL

---

pages/documentation/node-on-federalist.md

- Update the "Node on Federalist" doc to reflect the recent change to NodeJS 16.x Gallium LTS
/cc @hursey013  - You mentioned in Slack that Federalist recently began running NodeJS 16 instead of 14 and I noticed this doc was out of date.

Update current NodeJS LTS version
